# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goku < Formula
  desc "Compliant CI/CD for AI agents"
  homepage ""
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/goku/releases/download/v0.5.0/goku_Darwin_x86_64.tar.gz"
      sha256 "38b48046fb9ea47854070e00c6067f9d192aef7664bf12611e3fdaabb7ab2c29"

      define_method(:install) do
        bin.install "goku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/goku/releases/download/v0.5.0/goku_Darwin_arm64.tar.gz"
      sha256 "08158e13fe32cea4f12d3a87dedf7605a6530ea1b07f013fcba1c3c5d0cc7992"

      define_method(:install) do
        bin.install "goku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/goku/releases/download/v0.5.0/goku_Linux_x86_64.tar.gz"
      sha256 "825c5235e6386240abdc07988a1566bcf21be618856f633524204aefd0b71ebb"
      define_method(:install) do
        bin.install "goku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/goku/releases/download/v0.5.0/goku_Linux_arm64.tar.gz"
      sha256 "42ae4834579db5ad73c8e0ee0aa27d03d8bcd0920b6dce55af0f0944c7bc598b"
      define_method(:install) do
        bin.install "goku"
      end
    end
  end

  test do
    system "#{bin}/goku", "version"
  end
end
